name: Apple

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *' 

jobs:
  process-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Environment
        run: sudo apt-get install -y grep

      - name: Download files
        run: |
          curl https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/apple.txt -o apple1.txt
          curl https://raw.githubusercontent.com/yuumimi/rules/release/surge/apple.txt -o apple2.txt

      - name: Remove duplicates from second file
        run: |
          grep -Fvxf apple1.txt apple2.txt > Apple_Proxy.txt

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Apple_Proxy.txt
          git commit -m "Update Apple_Proxy.txt with deduplicated entries" || exit 0
          git push
