name: Domain-Set

on:
  workflow_dispatch:
  schedule:
    - cron: '04 21 * * *'  # UTC 时间21点，对应北京时间每天5点

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download and process file
      run: |
        curl -s https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules_domainset.txt -o Adrules_Domain.txt
        sed -i 's/^+//' Adrules_Domain.txt
        # echo ".mcdn.bilivideo.cn" >> Adrules_Domain.txt
        # echo ".szbdyd.com" >> Adrules_Domain.txt
        #echo ".chat.bilibili.com" >> Adrules_Domain.txt

    - name: Commit changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add Adrules_Domain.txt
        git commit -m "Update Adrules_Domain.txt"|| exit 0
        git push
