name: GameDownload

on:
  workflow_dispatch:
  schedule:
    - cron: '12 21 * * *' 

jobs:
  merge-domains:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch domainset/cdn.conf
        run: curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Game/GameDownloadCN/GameDownloadCN_No_Resolve.yaml -o GameDownloadCN.conf

      - name: Fetch domainset/download.conf
        run: curl -sL https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/SteamCN/SteamCN_No_Resolve.yaml -o SteamCN.conf

      - name: Combine Files
        run: cat SteamCN.conf GameDownloadCN > GameDownload.yaml

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add GameDownload.yaml
          git commit -m "Update GameDownload.yaml"|| exit 0
          git push
