name: telegram

on:
  workflow_dispatch:
  schedule:
    - cron: '15 21 * * *' 

jobs:
  merge-domains:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch domainset/telegramip.conf
        run: curl -sL https://ruleset.skk.moe/List/ip/telegram.conf -o telegramip.conf

      - name: Fetch domainset/telegramdomain.conf
        run: curl -sL https://ruleset.skk.moe/List/non_ip/telegram.conf -o telegramdomain.conf

      - name: Combine Files
        run: cat telegramip.conf telegramdomain.conf > telegram.txt

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add telegram.txt
          git commit -m "Update telegram.txt"|| exit 0
          git push
